import React from 'react'

function May17() {
    // the interview is about a python today


    // TYPE CASTING in the python str() , int()

    // PY python source fie
    // PYC files are byte file generated by the compailer

    // list is an array , dictionaries is an objects

    //  dict.items() will be used in the python 
    // The dict.items() method does not take any arguments. It returns a view object, which is an iterable that can be used in 
    // loops or converted to other data structures like lists.

    // while using this we can iterate the objects like an array 

    // dict.key() keys can access an array
    // dict.value() values can access in an array


    // Types of Namespaces in python
    // Built-in Namespace
    //print, len, Exception reaal time examples

    // Global Namespace
    // Contains functions, variables, classes defined at the top-level of a module.

    // Local Namespace
    // Contains local variables defined inside that function.

    // Enclosing Namespace
    // For nested functions, the inner function has access to variables in its enclosing function's namespace.


//     x = "global"  # Global namespace

// def outer():
//     x = "enclosing"  # Enclosing namespace

//     def inner():
//         x = "local"  # Local namespace
//         print("Inner:", x)

//     inner()
//     print("Outer:", x)

// outer()
// print("Global:", x)


// SIMPLY PY FUNCTION WITH CLASS
// class Fruit():
//     def __init__(self, price , quantity):
//         self.price = price
//         self.quantity = quantity
    
//     def calculate_quantity(self):
//         return self.quantity * self.price
        
// p = Fruit(10,5)
// print(p.calculate_quantity())


// INDEXING

// text = "Python"
// print(text[0])   # P
// print(text[3])   # h
// print(text[-1])  # n (last character)

// SLICING

// numbers = [10, 20, 30, 40, 50, 60]

// print(numbers[1:4])     # [20, 30, 40]
// print(numbers[:3])      # [10, 20, 30]
// print(numbers[::2])     # [10, 30, 50]
// print(numbers[-3:])     # [40, 50, 60]


// REGULAR EXPRESSION NEED TO IMPORT re in a python file


  return (
    <div>May17</div>
  )
}

export default May17